server:
  port: 9192

spring:
  datasource:
    username: root
    password: 0911895833yhk
    url: jdbc:mysql://localhost:3306/megenagna_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 5KB

  security:
    user:
      name: admin     # Custom username
      password: admin123 # Custom password
